# Generated by Django 6.0.6 on 2026-06-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('service', models.CharField(choices=[('web', 'Web Development'), ('design', 'Designing & Canva'), ('ai', 'AI & Computer Vision'), ('marketing', 'Digital Marketing'), ('ebook', 'eBook Writing'), ('dispatch', 'Truck Dispatch Training'), ('other', 'Other')], max_length=50)),
                ('budget', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
